server:
  port: 9098

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    url: jdbc:mysql://127.0.0.1:3306/chess?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1

websocket:
  port: 9097