server:
  port: 9098

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    url: jdbc:mysql://127.0.0.1:3306/chess?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1

websocket:
  port: 9097

yao-xin:
  endpoint: http://47.112.238.235:10018/open
  app-id: yx4b11c08aa09d44ed

github:
  client-id: 5176faf64742ae0bfe84
  client-secret: 784d4715dd756c7ae87b69c24ad822bab9702c45

app-url: http://180.76.185.34/


avatar:
  path: /avatar
  dir: /home/chinese_chess/avatars