spring:
  profiles:
    active: @profiles.active@

servlet:
  context-path: /

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.hulang1024.chinesechessserver.user
